Marketplace.WebApp/Controllers/OffersController.cs
using Marketplace.Core.Domain;
using Marketplace.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Marketplace.WebApp.Controllers
{
    [Authorize]
    public class OffersController : Controller
    {
        public IConfiguration Configuration;
        private UserManager<ApplicationUser> _userManager;
        public OffersController(IConfiguration configuration, UserManager<ApplicationUser> userManager)
        {
            Configuration = configuration;
            _userManager = userManager;
        }

        private async Task<string> GetEmailAsync()
        {
            string _plainrest = GetHostUrl().Content;

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = "";

            if (currentUser.Identity.IsAuthenticated)
            {
                return user.Email;
            }
            else
            {
                return "";
            }


        }

        private async Task<int> GetProfiledAsync()
        {
            string _plainrest = GetHostUrl().Content;

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = "";

            if (currentUser.Identity.IsAuthenticated)
            {
                currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            else
            {
                return -1;
            }

            ProfileVM profileModel = new ProfileVM();

            //Pobranie Usera
            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_plainrest}Profiles/uid?id={currentUserId}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        profileModel = JsonConvert.DeserializeObject<ProfileVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return (-1);
            }

            return (profileModel.ProfileId);

        }


        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {

            string _restpath = GetHostUrl().Content + CN();
            List<OfferVM> offersList = new List<OfferVM>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    offersList = JsonConvert.DeserializeObject<List<OfferVM>>(apiResponse);
                }
            }
            return View(offersList);
        }

        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            OfferVM s = new OfferVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    s = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                }
            }
            return View(s);

        }

        public async Task<IActionResult> Yours()
        {
            string _restpath = GetHostUrl().Content + CN();
            List<OfferVM> offersList = new List<OfferVM>();

            int profileID = await GetProfiledAsync();


            if (profileID == -1)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/pid?pid={profileID}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    offersList = JsonConvert.DeserializeObject<List<OfferVM>>(apiResponse);
                }
            }
            return View(offersList);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(OfferVM s, int id) //strongly type view
        {
            string _restpath = GetHostUrl().Content + CN();

            OfferVM ofResult = new OfferVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync(); //mozna zwrocic caly obiekt ktory zostal zedytowany
                        ofResult = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            OfferVM of = new OfferVM();

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            int profileid = await GetProfiledAsync();

 

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    of = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                }
            }

            if (of.ProfileId != profileid)
            {

                var isAdmin = _userManager.IsInRoleAsync(user, "admin").Result;
                if (isAdmin == false)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(of);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(OfferVM s, int id)
        {
            string _restpath = GetHostUrl().Content + CN();

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            OfferVM ofResult = new OfferVM();

            int profileid = await GetProfiledAsync();
            

            //if(s.ProfileId != profileid)
            //{
               
            //    var isAdmin = _userManager.IsInRoleAsync(user, "admin").Result;
            //    if (isAdmin == false)
            //    {
            //        return RedirectToAction(nameof(Index));
            //    }
            //}

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OfferVM s) //strongly type view
        {
            string _restpath = GetHostUrl().Content + CN();

            OfferVM ofResult = new OfferVM();

            int ProfileID = await GetProfiledAsync();

            s.ProfileId = ProfileID;
            s.CreatedDate = DateTime.Now;

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    Console.WriteLine(content);
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync(); //mozna zwrocic caly obiekt ktory zostal zedytowany
                        ofResult = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Details(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            string _plainrest = GetHostUrl().Content;

            OfferVM s = new OfferVM();

Marketplace.WebApp/Controllers/ProfilesController.cs
using Marketplace.Core.Domain;
using Marketplace.WebApp.Commands;
using Marketplace.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Marketplace.WebApp.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        public IConfiguration Configuration;
        private UserManager<ApplicationUser> _userManager;


        public ProfilesController(IConfiguration configuration, UserManager<ApplicationUser> userManager)
        {
            Configuration = configuration;
            _userManager = userManager;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }
        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }

        public async Task<IActionResult> IndexAsync()
        {
            string _restpath = GetHostUrl().Content + CN();
            string _plainrest = GetHostUrl().Content;

            ClaimsPrincipal currentUser = this.User;
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = _userManager.GetUserAsync(currentUser).Result;
            //var currentUserEmail = currentUser.FindFirst(ClaimTypes.Email).Value;


            ProfileVM model = new ProfileVM();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_restpath}/uid?id={currentUserId}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject < ProfileVM > (apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            ContactVM contactModel = new ContactVM();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_plainrest}contacts/pid?id={model.ProfileId}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        if (apiResponse == null)
                        {
                            contactModel = null;
                        }
                        contactModel = JsonConvert.DeserializeObject<ContactVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            model.contactVM = contactModel;
            model.Email = _userManager.GetEmailAsync(user).Result;
            return View(model);
        }

        public IActionResult Create()
        {
            ProfileCreateVM model = new ProfileCreateVM();
            model.getSex = model.getSexList();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProfileCreateVM profileCreateVM)
        {
            string _restpath = GetHostUrl().Content + CN();

            ClaimsPrincipal currentUser = this.User;
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;


            CreateProfile crProf = new CreateProfile()
            {
                Name = profileCreateVM.Name,
                Sex = profileCreateVM.SelectedSex,
                Surname = profileCreateVM.Surname,
                UserId = currentUserId
            };

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(crProf);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync($"{_restpath}/", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Marketplace.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Marketplace.Core.Domain;
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Marketplace</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marketplace</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Offers" asp-action="Index">Oferty</a>
                        </li>
                        @{ 
                            if (SignInManager.IsSignedIn(User))
                            {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Offers" asp-action="Yours">Twoje oferty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Twoje produkty</a>
                        </li>
                            }
                        }
                    </ul>
                </div>
                @* Elementy po prawej stronie w NavBarze*@
                <div class="navbar-collapse collapse order-3">
                    <ul class="navbar-nav ml-auto">
                        @{
                            if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-link text-light">
                                    <a class="text-light" asp-area="" asp-controller="Profiles" asp-action="Index" style="font-weight:bold">@User.Identity.Name</a>
                                </li>
                                <li class="nav-link">
                                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                                        <a href="javascript:document.getElementById('logoutForm').submit()" class="text-light">Wyloguj</a>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Zaloguj</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Marketplace | Bartłomiej Kopyść - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>