Marketplace.WebApp/Controllers/OffersController.cs
using Marketplace.Core.Domain;
using Marketplace.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Marketplace.WebApp.Controllers
{
    [Authorize]
    public class OffersController : Controller
    {
        public IConfiguration Configuration;
        private UserManager<ApplicationUser> _userManager;
        public OffersController(IConfiguration configuration, UserManager<ApplicationUser> userManager)
        {
            Configuration = configuration;
            _userManager = userManager;
        }

        private async Task<string> GetEmailAsync()
        {
            string _plainrest = GetHostUrl().Content;

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = "";

            if (currentUser.Identity.IsAuthenticated)
            {
                return user.Email;
            }
            else
            {
                return "";
            }


        }

        private async Task<int> GetProfiledAsync()
        {
            string _plainrest = GetHostUrl().Content;

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = "";

            if (currentUser.Identity.IsAuthenticated)
            {
                currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            else
            {
                return -1;
            }

            ProfileVM profileModel = new ProfileVM();

            //Pobranie Usera
            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_plainrest}Profiles/uid?id={currentUserId}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        profileModel = JsonConvert.DeserializeObject<ProfileVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return (-1);
            }

            return (profileModel.ProfileId);

        }


        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {

            string _restpath = GetHostUrl().Content + CN();
            List<OfferVM> offersList = new List<OfferVM>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    offersList = JsonConvert.DeserializeObject<List<OfferVM>>(apiResponse);
                }
            }
            return View(offersList);
        }

        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            OfferVM s = new OfferVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    s = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                }
            }
            return View(s);

        }

        public async Task<IActionResult> Yours()
        {
            string _restpath = GetHostUrl().Content + CN();
            List<OfferVM> offersList = new List<OfferVM>();

            int profileID = await GetProfiledAsync();


            if (profileID == -1)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/pid?pid={profileID}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    offersList = JsonConvert.DeserializeObject<List<OfferVM>>(apiResponse);
                }
            }
            return View(offersList);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(OfferVM s, int id) //strongly type view
        {
            string _restpath = GetHostUrl().Content + CN();

            OfferVM ofResult = new OfferVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync(); //mozna zwrocic caly obiekt ktory zostal zedytowany
                        ofResult = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            OfferVM of = new OfferVM();

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            int profileid = await GetProfiledAsync();

 

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    of = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                }
            }

            if (of.ProfileId != profileid)
            {

                var isAdmin = _userManager.IsInRoleAsync(user, "admin").Result;
                if (isAdmin == false)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(of);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(OfferVM s, int id)
        {
            string _restpath = GetHostUrl().Content + CN();

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            OfferVM ofResult = new OfferVM();

            int profileid = await GetProfiledAsync();
            

            //if(s.ProfileId != profileid)
            //{
               
            //    var isAdmin = _userManager.IsInRoleAsync(user, "admin").Result;
            //    if (isAdmin == false)
            //    {
            //        return RedirectToAction(nameof(Index));
            //    }
            //}

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OfferVM s) //strongly type view
        {
            string _restpath = GetHostUrl().Content + CN();

            OfferVM ofResult = new OfferVM();

            int ProfileID = await GetProfiledAsync();

            s.ProfileId = ProfileID;
            s.CreatedDate = DateTime.Now;

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(s);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    Console.WriteLine(content);
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync(); //mozna zwrocic caly obiekt ktory zostal zedytowany
                        ofResult = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Details(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            string _plainrest = GetHostUrl().Content;

            OfferVM s = new OfferVM();

Marketplace.WebApp/Controllers/OffersProductsController.cs
using Marketplace.Core.Domain;
using Marketplace.WebApp.Commands;
using Marketplace.WebApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Marketplace.WebApp.Controllers
{
    public class OffersProductsController : Controller
    {
        public IConfiguration Configuration;
        private UserManager<ApplicationUser> _userManager;
        public OffersProductsController(IConfiguration configuration, UserManager<ApplicationUser> userManager)
        {
            Configuration = configuration;
            _userManager = userManager;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string CN()
        {
            string cn = ControllerContext.RouteData.Values["controller"].ToString();
            return cn;
        }
        private async Task<int> GetProfiledAsync()
        {
            string _plainrest = GetHostUrl().Content;

            ClaimsPrincipal currentUser = this.User;
            var user = _userManager.GetUserAsync(currentUser).Result;
            var currentUserId = "";

            if (currentUser.Identity.IsAuthenticated)
            {
                currentUserId = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            else
            {
                return -1;
            }

            ProfileVM profileModel = new ProfileVM();

            //Pobranie Usera
            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_plainrest}Profiles/uid?id={currentUserId}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        profileModel = JsonConvert.DeserializeObject<ProfileVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                return (-1);
            }

            return (profileModel.ProfileId);
        }

        public async Task<IActionResult> AddProduct(int id)
        {
            int profileID = await GetProfiledAsync();

            if (profileID == -1)
            {
                return RedirectToAction("Index", "Home");
            }

            string _restpath = GetHostUrl().Content + CN();
            string _plainrest = GetHostUrl().Content;

            OfferVM off = new OfferVM();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_plainrest}Offers/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    off = JsonConvert.DeserializeObject<OfferVM>(apiResponse);
                }
            }

            // Pobranie listy produktów użytkownika

            List<ProductVM> productsList = new List<ProductVM>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{_plainrest}products/pid?pid={profileID}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    productsList = JsonConvert.DeserializeObject<List<ProductVM>>(apiResponse);
                }
            }

            List<SelectListItem> productItemList = new List<SelectListItem>();
            
            foreach (ProductVM pr in productsList)
            {
                SelectListItem n = new SelectListItem()
                {
                    Text = pr.Name,
                    Value = (pr.ProductId).ToString()
                };
                productItemList.Add(n);
            }

            OfferProductsVM OP = new OfferProductsVM()
            {
                OfferName = off.Name,
                getProduct = productItemList
            };

            return View(OP);
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(OfferProductsVM off)
        {
            //string _restpath = GetHostUrl().Content + CN();
            string _plainrest = GetHostUrl().Content;

            CreateOfferProduct cop = new CreateOfferProduct()
            {
                OfferId = off.OfferId,
                ProductId = Int32.Parse(off.SelectedProduct)
            };

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(cop);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync($"{_plainrest}Offers_Products", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync(); 
                    }
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }

            return RedirectToAction("Yours", "Offers");
        }
        

        
    }
}

Marketplace.WebApp/Views/Offers/Create.cshtml
@model Marketplace.WebApp.Models.OfferVM

<h4>OfferVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" />
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Marketplace.WebApp/Views/Offers/Delete.cshtml
@model Marketplace.WebApp.Models.OfferVM

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OfferVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfferId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfferId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Marketplace.WebApp/Views/Offers/Details.cshtml
@model Marketplace.WebApp.Models.OfferDetailsVM
@*@CommentModel IEnumerable<Marketplace.WebApp.Models.CommentVM>*@

<div>
    <h4>Oferta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            ID oferty
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OfferId)
        </dd>
        <dt class="col-sm-2">
            Nazwa
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OfferName)
        </dd>
        <dt class="col-sm-2">
            Cena
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OfferPrice)
        </dd>
        <dt class="col-sm-2">
            Aktywna?
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OfferActive)
        </dd>
        <dt class="col-sm-2">
            Data utworzenia
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
</div>

 
<div class="card">
    <div class="card-header">Dane kontaktowe</div>
    <div class="body" style="background-color: #ebebeb">
        <dl class="row">
            <dt class="col-sm-2">
                Imię
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                Nazwisko
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Surname)
            </dd>
            @{
                if (Model.contactVM != null)
                {
                    <dt class="col-sm-2">
                        Państwo
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(m => m.contactVM.Country)
                    </dd>
                    <dt class="col-sm-2">
                        Województwo
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(m => m.contactVM.County)
                    </dd>
                    <dt class="col-sm-2">
                        Miasto
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(m => m.contactVM.City)
                    </dd>
                    <dt class="col-sm-2">
                        Nr. telefonu
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(m => m.contactVM.Phone)
                    </dd>
                }
            }
        </dl>
    </div>
</div>
<br />

<div>
    <a asp-action="Index">Wróc do listy</a>
</div>

Marketplace.WebApp/Views/Offers/Edit.cshtml
@model Marketplace.WebApp.Models.OfferVM

<h4>OfferVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" />
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Marketplace.WebApp/Views/Offers/Index.cshtml
@model IEnumerable<Marketplace.WebApp.Models.OfferVM>
    <p>Przejrzyj dostępne oferty:</p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    ID oferty
                </th>
                <th>
                    Nazwa
                </th>
                <th>
                    Cena
                </th>
                <th>
                    Aktywna?
                </th>
                <th>
                    Data Utworzenia
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OfferId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.ActionLink("Szczególy", "Details", new { id = item.OfferId }) 
                        @{ 
                            if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Usuń", "Delete", new { id = item.OfferId })
                }
                        }

                </tr>
            }
        </tbody>
    </table>

Marketplace.WebApp/Views/Offers/Yours.cshtml
@model IEnumerable<Marketplace.WebApp.Models.OfferVM>

<p>
    <a asp-action="Create">Stórz nową ofertę</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                ID oferty
            </th>
            <th>
                Nazwa
            </th>
            <th>
                Cena
            </th>
            <th>
                Aktywna?
            </th>
            <th>
                Data Utworzenia
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OfferId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.OfferId }) |
                @Html.ActionLink("Szczególy", "Details", new { id = item.OfferId }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.OfferId }) |
                @Html.ActionLink("Dodaj produkt", "AddProduct", "OffersProducts", new { id = item.OfferId })
            </td>
        </tr>
}
    </tbody>
</table>